version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-by-zahin
    ports:
      - "5672:5672"
      - "15675:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: on-failure:2

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service-by-zahin
    ports:
      - "5015:5015"
    environment:
      - PORT=5015
      - MONGO_URI=mongodb+srv://admin:lPUXdwbhFnFtaHnH@cluster0.u3psp.mongodb.net/product_service
      - JWT_ACCESS_SECRET=yourAccessSecretHere
      - JWT_REFRESH_SECRET=yourRefreshSecretHere
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - JWT_ACCESS_SECRET=yourAccessSecretHere
      - JWT_REFRESH_SECRET=yourRefreshSecretHere
    depends_on:
      - rabbitmq
    restart: on-failure:3

  product-service:
    build:
      context: ./product-service
    container_name: product-service-by-zahin
    ports:
      - "5016:5016"
    environment:
      - PORT=5016
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/product_service_zahin
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - JWT_ACCESS_SECRET=yourAccessSecretHere
      - JWT_REFRESH_SECRET=yourRefreshSecretHere
    depends_on:
      - rabbitmq
      - auth-service
    restart: on-failure:3
